### ISSUE TITLE
I don't like all the checks being classes anymore

### ISSUE THREAD

**Issue by rdbende** [rdbende/flake8-tkinter#5]
At first it seemed a good idea to split each check into a separate class, but now it led to a lot of boilerplate code.

**Comment by rdbende** [comment]
I kinda like what `flake8-simplify` does.

**Comment by insolor** [comment]
I've not checked the code yet thoroughly, but as far as I see, there are only static and class methods are used, so I think you can just convert these classes into flat modules (just modules with functions) and treat them as classes with static functions, so imports will change from `from .checkers.TK102 import TK102` to `from .checkers import TK102` (or something like that, I haven't checked it). It will make code a bit more clear, IMO. Probably these modules will still correspond to the `CheckerBase` protocol, from the point of view of linters.

Though some checkers are inherited from one another, but `super()` is not used, so I don't know why it's done, and it is possible that something will break if you change such class to a flat module, I'm not sure.

P.S. now I see, some methods are inherited from TK111. Probably such inheritance could be emulated with imports.

**Comment by rdbende** [comment]
> Though some checkers are inherited from one another

This is because checkers have a `detect`, a `get_pos`, a `get_data` and a `get_message` method. The later 3 is used to generate the error message, but they are sometimes need to generate almost the same message, and it's just simpler to inherit them, than write the method again.

I think I'm gonna leave the checker functions in separate files, but make them a single function, that either returns None, or an error object.

`flake8-simplify` does this like this:
```python
def visit_Expr(self, node: ast.Expr) -> None:
    self.errors += get_sim112(node)
    self.generic_visit(node)
```

**Comment by rdbende** [comment]
Done with #7
