### ISSUE TITLE
tag_bind + statement with body in loop

### ISSUE THREAD

**Issue by Akuli** [rdbende/flake8-tkinter#8]
`flake8 --select=TK` emits no errors for this:

```python3
import tkinter

text = tkinter.Text()
for lel in range(500):
    if True:
        text.tag_bind("foo" + str(lel), print)
```

**Comment by rdbende** [comment]
Happens in with and try blocks too. ~Should recurse inside them.~ Should just check if there's a loop in its ancestry.
